### ISSUE TITLE
Solicitação de colaboração

### ISSUE THREAD

**Issue by RinaldoHub** [RinaldoHub/GCMS-Rinaldo-Bezerra#1]
@ramidedantas 

Olá, professor. Solicito que adicione seu nome como colaborador no README.

[README](https://github.com/RinaldoHub/GCMS-Rinaldo-Bezerra/edit/main/README.md)

**Comment by ramidedantas** [comment]
OK @RinaldoHub. Mude a descrição já que é o seu repositório, não da turma. Pode fechar o chamdo.
